"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',

    # Your apps
    'apps.chat',
    'apps.users',
    'apps.events',
    'apps.roommate',
    'apps.accounts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST be first

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}
AUTH_USER_MODEL = "users.CustomUser"
from datetime import timedelta

# ─────────────────────────────────────────────
# EMAIL CONFIGURATION
# ─────────────────────────────────────────────

# During development, emails are printed to the terminal console.
# No real email is sent. You will see the full email content in your
# runserver terminal window — copy the token from there to test.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# These values appear as the sender in verification emails.
DEFAULT_FROM_EMAIL = "Tribal <noreply@tribal.app>"
EMAIL_HOST_USER = "noreply@tribal.app"

# ── For production, replace the above EMAIL_BACKEND with: ──
#
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"          # or SendGrid, Mailgun, etc.
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "your@gmail.com"
# EMAIL_HOST_PASSWORD = "your_app_password"   # use env variable, never hardcode
#
# For SendGrid specifically:
# EMAIL_HOST = "smtp.sendgrid.net"
# EMAIL_HOST_USER = "apikey"
# EMAIL_HOST_PASSWORD = os.environ.get("SENDGRID_API_KEY")

# The base URL of your frontend, used to build the verification link.
# In production this would be: https://yourdomain.com
FRONTEND_URL = "http://localhost:3000"

REST_FRAMEWORK = {
    # Sets JWT as the default authentication method for all API views.
    # Any view using DRF's permission classes will automatically check
    # the Authorization: Bearer <token> header.
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # By default, only authenticated users can access API views.
    # You can override this per-view using permission_classes=[AllowAny].
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    # Access token expires in 60 minutes.
    # The client must use the refresh token to get a new one after expiry.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),

    # Refresh token expires in 7 days.
    # After 7 days the user must log in again.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    # When True, every time the refresh token is used to get a new
    # access token, a new refresh token is also issued (rotating refresh).
    # This is a security best practice.
    "ROTATE_REFRESH_TOKENS": True,

    # When True, the old refresh token is added to a blacklist after rotation
    # so it can't be reused. Requires 'rest_framework_simplejwt.token_blacklist'
    # in INSTALLED_APPS if you want to use this feature later.
    "BLACKLIST_AFTER_ROTATION": False,

    # The algorithm used to sign JWTs. HS256 = HMAC with SHA-256.
    "ALGORITHM": "HS256",

    # The field in the JWT payload that identifies the user.
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
CORS_ALLOW_ALL_ORIGINS = True