# Generated by Django 6.0.5 on 2026-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_alter_userlocation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
