# Generated by Django 6.0.5 on 2026-08-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_alter_userlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
    ]
