# Generated by Django 6.0.5 on 2026-08-21 10:49

import apps.users.models
import apps.users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_image_unique_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='', storage=apps.users.storage.SupabaseStorage(), upload_to=apps.users.models.profile_image_upload_path),
        ),
    ]
