# Generated by Django 6.0.5 on 2026-07-05 08:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_seed_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_matches_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_matches_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-compatibility_score'],
                'indexes': [models.Index(fields=['user', 'compatibility_score'], name='roommate_ro_user_id_618a81_idx')],
                'unique_together': {('user', 'matched_user')},
            },
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.PositiveIntegerField()),
                ('budget_max', models.PositiveIntegerField()),
                ('sleep_schedule', models.CharField(choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('flexible', 'Flexible')], max_length=20)),
                ('wake_time', models.TimeField()),
                ('smoking', models.CharField(choices=[('non_smoker', 'Non-Smoker'), ('smoker', 'Smoker'), ('occasional', 'Occasional')], max_length=20)),
                ('drinking', models.CharField(choices=[('non_drinker', 'Non-Drinker'), ('drinker', 'Drinker'), ('social', 'Social Drinker')], max_length=20)),
                ('cleanliness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('noise_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('guests_preference', models.CharField(choices=[('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('frequently', 'Frequently')], max_length=20)),
                ('food_preference', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('no_preference', 'No Preference')], max_length=20)),
                ('pets', models.CharField(choices=[('has_pets', 'Has Pets'), ('no_pets', 'No Pets'), ('okay_with_pets', 'Okay With Pets'), ('not_okay_with_pets', 'Not Okay With Pets')], max_length=30)),
                ('study_habit', models.CharField(choices=[('quiet', 'Needs Quiet'), ('background_noise_ok', 'Background Noise Okay'), ('group_study', 'Group Study'), ('rarely_studies_at_home', 'Rarely Studies At Home')], max_length=30)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('any', 'Any')], default='any', max_length=20)),
                ('room_type_preference', models.CharField(choices=[('private_room', 'Private Room'), ('shared_room', 'Shared Room'), ('entire_place', 'Entire Place'), ('any', 'Any')], default='any', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='roommate_profiles', to='users.interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sleep_schedule'], name='roommate_ro_sleep_s_eff577_idx'), models.Index(fields=['smoking'], name='roommate_ro_smoking_2ee9ff_idx'), models.Index(fields=['is_active'], name='roommate_ro_is_acti_7fe2b1_idx')],
            },
        ),
    ]
