# Generated by Django 6.0.5 on 2026-07-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_activity_latitude_activity_longitude_activity_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tags',
        ),
    ]
