# Generated by Django 6.0.5 on 2026-08-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_activity_latitude_activity_longitude_activity_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join', 'Someone joined your activity'), ('match', 'New activity matches your interests'), ('reminder', 'Activity reminder'), ('sos', 'SOS emergency alert')], max_length=20),
        ),
    ]
