"""
Tests for apps/roommate/ml/tribal_ml_recommender.py against the final
domain-weighted (feature_space_version="domain_weighted_v1") artifacts.

Run with:
    pytest apps/roommate/tests/test_tribal_ml_recommender.py -v

Requires: pytest, numpy, pandas, scikit-learn, and the three .pkl
artifacts present in apps/roommate/ml/ (generated by
train_kmeans_domain_weighted.py). Does NOT require Django — this module
has no Django dependency.
"""
import copy
import pickle
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from apps.roommate.ml import tribal_ml_recommender as rec

_ML_DIR = Path(rec.__file__).resolve().parent
_PROJECT_ROOT = _ML_DIR.parents[2]
_DATASET_PATH = _PROJECT_ROOT / "dataset.csv"


BASE_PROFILE = {
    "gender": "male",
    "budget_min": 11000,
    "budget_max": 16000,
    "sleep_schedule": "night_owl",
    "wake_time": "08:30",
    "smoking": "non_smoker",
    "drinking": "social",
    "cleanliness": 4,
    "noise_level": 2,
    "guests_preference": "sometimes",
    "food_preference": "vegetarian",
    "pets": "okay_with_pets",
    "study_habit": "quiet",
    "interests": ["Hiking", "Music"],
    # present in real service.py dicts, must be ignored by ML:
    "gender_preference": "any",
    "room_type_preference": "any",
}


def make_profile(**overrides):
    p = copy.deepcopy(BASE_PROFILE)
    p.update(overrides)
    return p


# ─────────────────────────────────────────────────────────────────────
# 1. Identical profiles -> distance 0, compatibility 100
# ─────────────────────────────────────────────────────────────────────

def test_identical_profiles_are_perfectly_compatible():
    a = make_profile()
    b = make_profile()
    result = rec.pairwise_compatibility(a, b)
    assert result["distance"] == 0.0
    assert result["compatibility_score"] == 100.0


# ─────────────────────────────────────────────────────────────────────
# 2. Symmetry
# ─────────────────────────────────────────────────────────────────────

def test_compatibility_is_symmetric():
    a = make_profile()
    b = make_profile(gender="female", sleep_schedule="early_bird", smoking="smoker")
    ab = rec.pairwise_compatibility(a, b)
    ba = rec.pairwise_compatibility(b, a)
    assert ab["distance"] == pytest.approx(ba["distance"])
    assert ab["compatibility_score"] == pytest.approx(ba["compatibility_score"])


# ─────────────────────────────────────────────────────────────────────
# 3. Deterministic transformation
# ─────────────────────────────────────────────────────────────────────

def test_transform_is_deterministic():
    a = make_profile()
    v1 = rec.transform_user(a)
    v2 = rec.transform_user(a)
    assert np.array_equal(v1, v2)


# ─────────────────────────────────────────────────────────────────────
# 4. Final feature dimension
# ─────────────────────────────────────────────────────────────────────

def test_transformed_vector_shape_is_1_by_47():
    a = make_profile()
    v = rec.transform_user(a)
    assert v.shape == (1, 47)


# ─────────────────────────────────────────────────────────────────────
# 5. Domain weighting actually present in the transformed vector
# ─────────────────────────────────────────────────────────────────────

def test_domain_weights_are_applied_in_transformed_vector():
    """Same profile except gender flips -> the change should land only in
    the gender domain's column slice, and the magnitude of that change
    should reflect the gender domain weight (5.0), not an arbitrary
    scale."""
    a = make_profile(gender="male")
    b = make_profile(gender="female")
    va = rec.transform_user(a)[0]
    vb = rec.transform_user(b)[0]

    domain_slices = rec._PREPROCESSOR["domain_slices"]
    diff = va - vb

    for domain, (lo, hi) in domain_slices.items():
        segment_diff = diff[lo:hi]
        if domain == "gender":
            assert np.any(np.abs(segment_diff) > 1e-9), "gender segment should differ"
        else:
            assert np.allclose(segment_diff, 0.0), f"{domain} segment should NOT differ"

    # gender is the highest-weighted domain (5.0) -- confirm it's recorded
    # as such in the artifact actually driving inference.
    assert rec._DOMAIN_WEIGHTS["gender"] == 5.0
    assert rec._DOMAIN_WEIGHTS["gender"] == max(rec._DOMAIN_WEIGHTS.values())


def test_gender_mismatch_costs_more_than_five_domain_lifestyle_mismatch():
    """Documents the deliberate, disclosed design property: a single
    gender mismatch reduces compatibility more than simultaneously
    mismatching sleep_schedule, smoking, food_preference, study_habit,
    and pets."""
    a = make_profile()
    gender_mismatch = make_profile(gender="female")
    lifestyle_mismatch = make_profile(
        sleep_schedule="early_bird", smoking="smoker",
        food_preference="non_vegetarian", study_habit="group_study",
        pets="not_okay_with_pets",
    )
    r_gender = rec.pairwise_compatibility(a, gender_mismatch)
    r_lifestyle = rec.pairwise_compatibility(a, lifestyle_mismatch)
    assert r_gender["compatibility_score"] < r_lifestyle["compatibility_score"]


# ─────────────────────────────────────────────────────────────────────
# 6. Cluster prediction
# ─────────────────────────────────────────────────────────────────────

# ─────────────────────────────────────────────────────────────────────
# 6. Model loading + cluster prediction
# ─────────────────────────────────────────────────────────────────────

def test_kmeans_model_is_loaded_from_pickle():
    assert rec._MODEL is not None
    assert hasattr(rec._MODEL, "predict")
    assert getattr(rec._MODEL, "feature_space_version", None) == "domain_weighted_v1"


def test_predict_cluster_returns_valid_cluster_id():
    a = make_profile()
    cluster = rec.predict_cluster(a)
    assert isinstance(cluster, int)
    assert 0 <= cluster < 3  # K=3


# ─────────────────────────────────────────────────────────────────────
# 7. Different-cluster candidates are never filtered out (fallback)
# ─────────────────────────────────────────────────────────────────────

def test_different_cluster_candidates_remain_available_as_fallback():
    """Cluster membership affects RANKING (via CLUSTER_SAME_BONUS), not
    eligibility -- a candidate in a different cluster from the target
    must still be returned, never silently dropped."""
    target = make_profile()
    other_gender_same_lifestyle = make_profile(gender="female")
    candidates = [(1, other_gender_same_lifestyle)]
    matches = rec.find_matches_among(target, candidates, top_n=10)
    assert len(matches) == 1
    assert matches[0]["user_id"] == 1
    assert "cluster" in matches[0]
    assert "target_cluster" in matches[0]
    assert "recommendation_score" in matches[0]


# ─────────────────────────────────────────────────────────────────────
# 7b. CRITICAL: cluster membership materially affects final ranking
# ─────────────────────────────────────────────────────────────────────

def test_cluster_aware_ranking_prioritizes_same_cluster_candidate(monkeypatch):
    """CRITICAL controlled test: two candidates have an IDENTICAL,
    below-ceiling compatibility_score to the target (same lifestyle
    deltas, by construction), but their predicted clusters are forced
    apart via a monkeypatched model.predict. This proves the
    cluster-aware ranking bonus -- not just compatibility_score --
    decides final order, i.e. K-Means is not merely called and then
    ignored. Candidate ids are deliberately assigned so that "same
    cluster wins" and "first in input order wins" make DIFFERENT
    predictions, ruling out sort-stability as an alternative
    explanation."""
    target = make_profile()
    candidate_a = make_profile(sleep_schedule="early_bird", smoking="smoker")
    candidate_b = make_profile(sleep_schedule="early_bird", smoking="smoker")
    candidates = [(1, candidate_a), (2, candidate_b)]

    def fake_predict(matrix):
        if matrix.shape[0] == 1:
            return np.array([0])
        return np.array([1, 0])  # candidate 1 (id=1) -> different, candidate 2 (id=2) -> same as target

    monkeypatch.setattr(rec._MODEL, "predict", fake_predict)

    matches = rec.find_matches_among(target, candidates, top_n=10)
    by_id = {m["user_id"]: m for m in matches}

    assert by_id[1]["compatibility_score"] == by_id[2]["compatibility_score"]
    assert by_id[1]["compatibility_score"] < 95.0
    assert by_id[2]["compatibility_score"] == by_id[1]["compatibility_score"]

    assert by_id[2]["recommendation_score"] == pytest.approx(
        by_id[1]["recommendation_score"] + rec.CLUSTER_SAME_BONUS
    )
    assert matches[0]["user_id"] == 2
    assert matches[0]["cluster"] == matches[0]["target_cluster"]
    assert matches[1]["cluster"] != matches[1]["target_cluster"]


# ─────────────────────────────────────────────────────────────────────
# 8. Candidate ranking: closer profiles rank higher
# ─────────────────────────────────────────────────────────────────────

def test_closer_profiles_rank_higher():
    target = make_profile()
    identical = make_profile()
    somewhat_different = make_profile(noise_level=3, cleanliness=3)
    very_different = make_profile(
        gender="female", budget_min=25000, budget_max=35000,
        sleep_schedule="early_bird",
    )
    candidates = [
        (1, very_different),
        (2, identical),
        (3, somewhat_different),
    ]
    matches = rec.find_matches_among(target, candidates, top_n=10)
    ranked_ids = [m["user_id"] for m in matches]
    assert ranked_ids == [2, 3, 1]
    scores = [m["compatibility_score"] for m in matches]
    assert scores == sorted(scores, reverse=True)
    rec_scores = [m["recommendation_score"] for m in matches]
    assert rec_scores == sorted(rec_scores, reverse=True)


# ─────────────────────────────────────────────────────────────────────
# 9. Malformed candidate does not crash the whole batch
# ─────────────────────────────────────────────────────────────────────

def test_malformed_candidate_is_skipped_not_fatal():
    target = make_profile()
    good = make_profile()
    malformed = make_profile()
    del malformed["budget_min"]  # missing required field
    candidates = [(1, good), (2, malformed)]
    matches = rec.find_matches_among(target, candidates, top_n=10)
    ids = [m["user_id"] for m in matches]
    assert 1 in ids
    assert 2 not in ids


def test_transform_user_raises_on_missing_required_field():
    bad = make_profile()
    del bad["sleep_schedule"]
    with pytest.raises(rec.TribalRecommenderError):
        rec.transform_user(bad)


def test_transform_user_raises_on_invalid_wake_time_type():
    bad = make_profile(wake_time=12345)
    with pytest.raises(rec.TribalRecommenderError):
        rec.transform_user(bad)


@pytest.mark.parametrize("wake_time_value", ["08:30", "08:30:00"])
def test_wake_time_string_formats_are_handled_consistently(wake_time_value):
    a = make_profile(wake_time=wake_time_value)
    v = rec.transform_user(a)
    assert v.shape == (1, 47)


def test_wake_time_datetime_time_and_datetime_are_handled():
    import datetime
    a1 = make_profile(wake_time=datetime.time(8, 30))
    a2 = make_profile(wake_time=datetime.datetime(2024, 1, 1, 8, 30))
    a3 = make_profile(wake_time="08:30")
    v1 = rec.transform_user(a1)
    v2 = rec.transform_user(a2)
    v3 = rec.transform_user(a3)
    assert np.array_equal(v1, v2)
    assert np.array_equal(v1, v3)


# ─────────────────────────────────────────────────────────────────────
# 10. Artifact mismatch fails clearly
# ─────────────────────────────────────────────────────────────────────

def test_artifact_version_mismatch_raises_clear_error(tmp_path, monkeypatch):
    """Simulates a stale preprocessor (wrong feature_space_version)
    paired with the current model -- must fail loudly at load time."""
    with open(_ML_DIR / "tribal_preprocessor.pkl", "rb") as f:
        preprocessor = pickle.load(f)
    stale_preprocessor = dict(preprocessor)
    stale_preprocessor["feature_space_version"] = "some_old_version"

    stale_dir = tmp_path / "stale_artifacts"
    stale_dir.mkdir()
    shutil.copy(_ML_DIR / "tribal_kmeans_model.pkl", stale_dir / "tribal_kmeans_model.pkl")
    shutil.copy(_ML_DIR / "tribal_cluster_data.pkl", stale_dir / "tribal_cluster_data.pkl")
    with open(stale_dir / "tribal_preprocessor.pkl", "wb") as f:
        pickle.dump(stale_preprocessor, f)

    import importlib
    monkeypatch.setattr(rec, "_ARTIFACT_DIR", stale_dir, raising=False)
    monkeypatch.setattr(rec, "_MODEL_PATH", stale_dir / "tribal_kmeans_model.pkl", raising=False)
    monkeypatch.setattr(rec, "_PREPROCESSOR_PATH", stale_dir / "tribal_preprocessor.pkl", raising=False)
    monkeypatch.setattr(rec, "_CLUSTER_DATA_PATH", stale_dir / "tribal_cluster_data.pkl", raising=False)

    with pytest.raises(rec.TribalRecommenderError, match="feature_space_version"):
        rec._load_artifacts()


def test_missing_artifact_file_raises_clear_error(tmp_path, monkeypatch):
    empty_dir = tmp_path / "empty"
    empty_dir.mkdir()
    monkeypatch.setattr(rec, "_MODEL_PATH", empty_dir / "tribal_kmeans_model.pkl", raising=False)
    with pytest.raises(rec.TribalRecommenderError, match="Missing model artifact"):
        rec._load_artifacts()


# ─────────────────────────────────────────────────────────────────────
# 11. CRITICAL: train-vs-inference consistency check
# ─────────────────────────────────────────────────────────────────────

@pytest.mark.skipif(not _DATASET_PATH.exists(), reason="dataset.csv not available")
def test_train_vs_inference_produces_identical_vector_for_a_training_row():
    """Takes a real row from the training data, runs it through the
    LIVE inference _transform(), and asserts it exactly reproduces the
    corresponding row of the feature matrix that was actually clustered
    during training (persisted in tribal_cluster_data.pkl)."""
    with open(_ML_DIR / "tribal_cluster_data.pkl", "rb") as f:
        cluster_data = pickle.load(f)
    training_matrix = cluster_data["feature_matrix"]
    training_user_ids = list(cluster_data["user_ids"])

    df = pd.read_csv(_DATASET_PATH)

    for row_idx in (0, 1, 5000, 9999):
        row = df.iloc[row_idx]
        assert int(row["user_id"]) == training_user_ids[row_idx]

        user_data = {
            "gender": row["gender"],
            "budget_min": row["budget_min"],
            "budget_max": row["budget_max"],
            "sleep_schedule": row["sleep_schedule"],
            "wake_time": row["wake_time"],
            "smoking": row["smoking"],
            "drinking": row["drinking"],
            "cleanliness": row["cleanliness"],
            "noise_level": row["noise_level"],
            "guests_preference": row["guests_preference"],
            "food_preference": row["food_preference"],
            "pets": row["pets"],
            "study_habit": row["study_habit"],
            "interests": row["interests"],
        }
        inference_vector = rec.transform_user(user_data)[0]
        training_vector = training_matrix[row_idx]

        assert np.allclose(inference_vector, training_vector, atol=1e-8), (
            f"Row {row_idx}: inference transform does not match the "
            "vector actually used to train the model."
        )


# ─────────────────────────────────────────────────────────────────────
# Bonus: excluded fields never leak into the feature vector
# ─────────────────────────────────────────────────────────────────────

def test_gender_preference_and_room_type_preference_do_not_affect_vector():
    a = make_profile(gender_preference="any", room_type_preference="any")
    b = make_profile(gender_preference="female_only", room_type_preference="private")
    va = rec.transform_user(a)
    vb = rec.transform_user(b)
    assert np.array_equal(va, vb)
