# Generated by Django 6.0.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('safety', '0005_livelocationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='live_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='safety.livelocationsession'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('LIVE_LOCATION', 'Live Location')], default='TEXT', max_length=20),
        ),
    ]
